# Generated by Django 5.1.7 on 2025-03-17 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_remove_freelancer_category_freelancer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='job.category'),
        ),
    ]
