# Generated by Django 5.1.7 on 2025-03-17 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='username',
        ),
        migrations.AddField(
            model_name='apply',
            name='freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job.freelancer'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job.job'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='link',
            field=models.URLField(),
        ),
        migrations.AddConstraint(
            model_name='apply',
            constraint=models.UniqueConstraint(fields=('freelancer', 'job'), name='unique_application'),
        ),
    ]
