# Generated by Django 5.1.7 on 2025-03-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_remove_apply_email_remove_apply_username_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apply',
            name='unique_application',
        ),
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together={('freelancer', 'job')},
        ),
    ]
