# Generated by Django 5.1.7 on 2025-03-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_apply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.freelancer'),
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='card',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='category',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
