# Generated by Django 5.1.7 on 2025-03-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_alter_job_created_by_remove_freelancer_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='image',
            field=models.ImageField(default='img/blog/author.png', null=True, upload_to='img/freelancer/'),
        ),
    ]
